package event

import (
	"bytes"
	"encoding/json"
	"log"
	"net/http"
	"os"

	"github.com/bxcodec/faker/v3"
	"github.com/juanjoss/off-generator/model"
)

var registerEndpoint = os.Getenv("SERVICE_HOST") + "/api/register"

type UserRegistration struct {
}

type UserRegistrationRequest struct {
	User    *model.User  `json:"user"`
	Devices []*model.SSD `json:"devices"`
}

func (ur *UserRegistration) Handle() {
	/**
	used for limiting the number of SSD devices
	generated by faker
	*/
	_ = faker.SetRandomMapAndSliceMinSize(1)
	_ = faker.SetRandomMapAndSliceMaxSize(3)

	request := UserRegistrationRequest{
		User:    &model.User{},
		Devices: []*model.SSD{},
	}

	/**
	generating fake user
	*/
	err := faker.FakeData(&request.User)
	if err != nil {
		panic(err)
	}

	/**
	generating fake ssds
	*/
	err = faker.FakeData(&request.Devices)
	if err != nil {
		panic(err)
	}

	/**
	send registration to API
	*/
	jsonBody, err := json.Marshal(request)
	if err != nil {
		panic(err)
	}

	res, err := http.Post(
		registerEndpoint,
		"application/json",
		bytes.NewBuffer(jsonBody),
	)
	if err != nil {
		panic(err)
	}

	if res.StatusCode != http.StatusOK {
		log.Println("event failed")
	}
}

func (ur *UserRegistration) Type() string {
	return "user-registration"
}
