package event

import (
	"bytes"
	"encoding/json"
	"log"
	"net/http"
	"os"

	"github.com/bxcodec/faker/v3"
	"github.com/juanjoss/off-generator/model"
)

var registerEndpoint = os.Getenv("USERS_SERVICE") + "/register"

type UserRegistration struct{}

type UserRegistrationRequest struct {
	User    *model.User  `json:"user"`
	Devices []*model.SSD `json:"devices"`
}

func (ur *UserRegistration) Handle() {
	/*
		limiting the number of devices
		generated by faker
	*/
	_ = faker.SetRandomMapAndSliceMinSize(1)
	_ = faker.SetRandomMapAndSliceMaxSize(3)

	request := UserRegistrationRequest{
		User:    &model.User{},
		Devices: []*model.SSD{},
	}

	/*
		generating fake user
	*/
	err := faker.FakeData(&request.User)
	if err != nil {
		panic(err.Error())
	}

	/*
		generating fake device
	*/
	err = faker.FakeData(&request.Devices)
	if err != nil {
		panic(err.Error())
	}

	/*
		send registration to users service
	*/
	jsonBody, err := json.Marshal(request)
	if err != nil {
		panic(err.Error())
	}

	res, err := http.Post(
		registerEndpoint,
		"application/json",
		bytes.NewBuffer(jsonBody),
	)
	if err != nil {
		panic(err.Error())
	}

	if res.StatusCode != http.StatusOK {
		log.Println("event", ur.Type(), "failed")
	}
}

func (ur *UserRegistration) Type() string {
	return "user-registration"
}
